# Generated by Django 3.0.5 on 2022-06-29 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Name', models.CharField(max_length=64)),
                ('User_Pwd', models.CharField(max_length=10)),
            ],
        ),
    ]
